openapi: 3.0.0
info:
  title: Book Store API
  description: API to manage a book store.
  version: 1.0.0
servers:
  - url: https://api.bookstore.com/v1
paths:
  /books:
    get:
      summary: Get a list of books
      responses:
        '200':
          description: A list of books
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    title:
                      type: string
                      example: "The Great Gatsby"
                    author:
                      type: string
                      example: "F. Scott Fitzgerald"
